In [ ]:
import numpy as np

array1 = np.array([4, 5, 6, 8])
array2 = np.array([6, 9, 7, 3])

array_sum = array1 + array2
print(array_sum)
print(type(array_sum))

array_diff = array1 - array2
print(array_diff)
print(type(array_diff))

array_product = array1 * array2
print(array_product)
print(type(array_product))

[10 14 13 11]
<class 'numpy.ndarray'>
[-2 -4 -1  5]
<class 'numpy.ndarray'>
[24 45 42 24]
<class 'numpy.ndarray'>


In [23]:
array_1 = np.array([[4, 3, 5], [9, 5, 8]])
print(array_1)

print(array_1.size)   # Print the total number of elements in the array
print(array_1.ndim)   # Print the number of dimensions of the array
print(array_1.shape)  # Print the shape of the array (rows, columns)

print(array_1.dtype)  # Print the data type of the elements in the array

[[4 3 5]
 [9 5 8]]
6
2
(2, 3)
int64


In [24]:
array_2 = np.array([[[4, 5, 8],[11, 20, 13]], [[6, 9, 7],[3, 2, 1]]])

print(array_2.size)
print(array_2.ndim)
print(array_2.shape)

12
3
(2, 2, 3)


In [30]:
array_1 = np.array([6, 9, 4, 2])

print(array_1[3])  # Print the last element of the array

2


In [ ]:
array_1 = np.array([[4, 3, 5], [9, 8, 12]])
print(array_1[1][1])  # Accessing the element at row 1, column 1  # less efficient syntax
print(array_1[1, 1]) # Accessing the same element using a different syntax

8
8


In [46]:
array_2 = np.array([[[4, 5, 8],[11, 20, 13]], [[6, 9, 7],[3, 2, 1]]])
print(array_2[0,1, 1])
print(array_2[1,0, 2])  # Accessing the element at first array, second row, third column

20
7


In [ ]:
import numpy as np

arr = np.array([10, 50, 40, 20, 30])

condition = arr > 25

print(condition)  # Print the boolean array where condition is True or False
print(arr[condition])  # Print the elements of arr that satisfy the condition
print(arr[arr > 25])

print(arr[(arr > 25) & (arr < 45)])  # Print elements greater than 25 and less than 50

[False  True  True False  True]
[50 40 30]
[50 40 30]
[40 30]


In [26]:
# you are given the following array representing the body temperatures(in Celsius) of five patients over 3 time slots.(morning, afternoon, evening)
# 31 30 28
# 29 29 32
# 26 24 27
# 31 34 35
# 28 31 30
# Identify and extraact all temperatures reading grater than the daily avarage temperature using boolean indexing in nmpy array.

temperatures = np.array([[31, 30, 28],[29, 29, 32],[26, 24, 27],[31, 34, 35],[28, 31, 30]])
daily_avg = np.mean(temperatures)
print(daily_avg)

condition = temperatures > daily_avg
print(temperatures[condition])



29.666666666666668
[31 30 32 31 34 35 31 30]


In [59]:
import numpy as np

print(np.zeros((3, 4)))  # Create a 3x4 array filled with zeros
print(np.full((2, 3), 7))  # Create a 2x3 array filled with the value 7
print(np.ones((2, 3)))   # Create a 2x3 array filled


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
array_1 = np.empty((2, 3))  # Create an empty array with shape 2x3
print(array_1)  # The values in the empty array are uninitialized and may contain

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import pandas as pd

data = {
    'Name' : ['Alice', 'Bob', 'Charlie', 'David'],
    'Age' : [25, 30, 35, 40],
}

df = pd.DataFrame(data)  # Create a DataFrame from the dictionary
print(df)  # Print the DataFrame
print(type(df))  # Print the type of the DataFrame

print(df.loc[2, 'Age'])  # Access the value at row index 2 and column 'Age'

print(df.iloc[3, 0])  # Access the value at row index 2 and column index 1

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
<class 'pandas.core.frame.DataFrame'>
35
David
(4, 2)


In [55]:
data = {
    'Name' : ['Alice', 'Bob', 'Charlie', 'David'],
    'Age' : [25, 30, 35, 40],
}

df = pd.DataFrame(data, index=['student1', 'student2', 'student3', 'student4'])  # Create a DataFrame with custom index
print(df)  # Print the DataFrame with custom index
print(type(df))  # Print the type of the DataFrame with custom index
print(df.loc['student1'])
print()
print(df.loc[['student1','student2']]) # Access multiple rows by index labels(need to pass list of labels)

print()
print(df.iloc[0:2]) # Access multiple rows by index positions (slicing)
print()
print(df['Age'])  # Access the 'Age' column of the DataFrame
print()
print(df[['Name','Age']])  # Access the 'Age' column of the DataFrame
print()
print(df.size)  # Print the total number of elements in the DataFrame
print(df.shape)  # Print the shape of the DataFrame (rows, columns)
print(len(df))  # Print the number of rows in the DataFrame
print()
print(df.shape[0])  
print()
print(df.columns)  # Print the column names of the DataFrame
print(list(df.columns)) # conver the column names to a list
print(df.index)  # Print the index labels of the DataFrame

             Name  Age
student1    Alice   25
student2      Bob   30
student3  Charlie   35
student4    David   40
<class 'pandas.core.frame.DataFrame'>
Name    Alice
Age        25
Name: student1, dtype: object

           Name  Age
student1  Alice   25
student2    Bob   30

           Name  Age
student1  Alice   25
student2    Bob   30

student1    25
student2    30
student3    35
student4    40
Name: Age, dtype: int64

             Name  Age
student1    Alice   25
student2      Bob   30
student3  Charlie   35
student4    David   40

8
(4, 2)
4

4

Index(['Name', 'Age'], dtype='object')
['Name', 'Age']
Index(['student1', 'student2', 'student3', 'student4'], dtype='object')


In [57]:
arr = df.values  # Convert the DataFrame to a NumPy array
print(arr)  # Print the NumPy array representation of the DataFrame
print(type(arr))  # Print the type of the NumPy array

[['Alice' 25]
 ['Bob' 30]
 ['Charlie' 35]
 ['David' 40]]
<class 'numpy.ndarray'>


In [64]:
print(df.sum())  # Print the sum of each column in the DataFrame
print(df['Age'].mean())  # Print the mean of the 'Age' column
print(df['Age'].max())  # Print the maximum value in the 'Age' column


Name    AliceBobCharlieDavid
Age                      130
dtype: object
32.5
40


In [66]:
# how to add a new column to the DataFrame

df['City'] = ['Colombo', 'Kandy', 'Galle', 'Matara']  # Add a new column 'City' to the DataFrame
print(df)  # Print the updated DataFrame with the new column

             Name  Age     City
student1    Alice   25  Colombo
student2      Bob   30    Kandy
student3  Charlie   35    Galle
student4    David   40   Matara


In [68]:
# how to add a new row to the DataFrame

df.loc['student5'] = ['Manuth', 28, 'Horana'] 
print(df) 


             Name  Age     City
student1    Alice   25  Colombo
student2      Bob   30    Kandy
student3  Charlie   35    Galle
student4    David   40   Matara
student5   Manuth   28   Horana


In [69]:
filtered_df = df[df['Age'] > 30]  # Filter the DataFrame to include only rows where 'Age' is greater than 30
print(filtered_df)  # Print the filtered DataFrame

             Name  Age    City
student3  Charlie   35   Galle
student4    David   40  Matara


In [ ]:
df['Distance'] = [100, 200, 150, 300, 250] 

print(df[(df['Distance'] < 200) & (df['Age'] > 30)]) 

             Name  Age   City  Distance
student3  Charlie   35  Galle       150


In [99]:
# you are given the following Dataset representing the exam records of students.
# In a programming course.The data includes marks for 2 assignments and a final exam.

# studentID    Name     Assignment1  Assignment2  FinalExam
# 1001         Ayesha      78           85           90
# 1002         Nimal       65           70           72
# 1003         Tharindu    88           90           95
# 1004         Kasun       50           45           60
# 1005         Sashini     80           75           85

# write a python program using pandas to:
   # 1. Create a DataFrame using the given data.
   # 2. Display the Name of all students who scored more than 80 in the FinalExam.
   # 3. Calculate the average score of each students across all assessments and add it as a new column called 'Average'.
   # 4. Display the student(s) with the highest average score.
   # 5. Calculate and Display the Total marks if scored by all students in Assignment1.

import pandas as pd
data = {
    'studentID': [1001, 1002, 1003, 1004, 1005],
    'Name': ['Ayesha', 'Nimal', 'Tharindu', 'Kasun', 'Sashini'],
    'Assignment1': [78, 65, 88, 50, 80],
    'Assignment2': [85, 70, 90, 45, 75],
    'FinalExam': [90, 72, 95, 60, 85]
}

df = pd.DataFrame(data)

print(df[df['FinalExam'] > 80]['Name'])

df['Average'] = (df['Assignment1'] + df['Assignment2'] + df['FinalExam']) / 3
print(df)

highest_average  = df['Average'].max()
print(df[df['Average'] == highest_average])

print("Total Marks Assignment1 :", df['Assignment1'].sum())  



0      Ayesha
2    Tharindu
4     Sashini
Name: Name, dtype: object
   studentID      Name  Assignment1  Assignment2  FinalExam    Average
0       1001    Ayesha           78           85         90  84.333333
1       1002     Nimal           65           70         72  69.000000
2       1003  Tharindu           88           90         95  91.000000
3       1004     Kasun           50           45         60  51.666667
4       1005   Sashini           80           75         85  80.000000
   studentID      Name  Assignment1  Assignment2  FinalExam  Average
2       1003  Tharindu           88           90         95     91.0
Total Marks Assignment1 : 361


In [100]:
import pandas as pd
df = pd.read_csv('test.csv')  # Load the CSV file into a DataFrame
print(df)  # Print the DataFrame
print(type(df))  # Print the type of the DataFrame

          Name  Age Occupation
0     John Doe   30   Engineer
1   Jane Smith   25    Teacher
2  Bob Johnson   40     Doctor
3  Alice Brown   35     Artist
<class 'pandas.core.frame.DataFrame'>
